
package com.ibm.demotest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CeInterfaceService", targetNamespace = "http://ibm.com/demotest/", wsdlLocation = "http://10.6.1.66:50200/CeInterfaceService/CeInterface?wsdl=binding")
public class CeInterfaceService
    extends Service
{

    private final static URL CEINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException CEINTERFACESERVICE_EXCEPTION;
    private final static QName CEINTERFACESERVICE_QNAME = new QName("http://ibm.com/demotest/", "CeInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.1.66:50200/CeInterfaceService/CeInterface?wsdl=binding");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CEINTERFACESERVICE_WSDL_LOCATION = url;
        CEINTERFACESERVICE_EXCEPTION = e;
    }

    public CeInterfaceService() {
        super(__getWsdlLocation(), CEINTERFACESERVICE_QNAME);
    }

    public CeInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CEINTERFACESERVICE_QNAME, features);
    }

    public CeInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, CEINTERFACESERVICE_QNAME);
    }

    public CeInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CEINTERFACESERVICE_QNAME, features);
    }

    public CeInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CeInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CeInterface
     */
    @WebEndpoint(name = "CeInterfacePort")
    public CeInterface getCeInterfacePort() {
        return super.getPort(new QName("http://ibm.com/demotest/", "CeInterfacePort"), CeInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CeInterface
     */
    @WebEndpoint(name = "CeInterfacePort")
    public CeInterface getCeInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibm.com/demotest/", "CeInterfacePort"), CeInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CEINTERFACESERVICE_EXCEPTION!= null) {
            throw CEINTERFACESERVICE_EXCEPTION;
        }
        return CEINTERFACESERVICE_WSDL_LOCATION;
    }

}
