
package com.ibm.service.processhistory;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessHistoryServiceService", targetNamespace = "http://ibm.com/queryHistory/", wsdlLocation = "http://10.6.1.66:50200/ProcessHistoryServiceService/ProcessHistoryService?wsdl")
public class ProcessHistoryServiceService
    extends Service
{

    private final static URL PROCESSHISTORYSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSHISTORYSERVICESERVICE_EXCEPTION;
    private final static QName PROCESSHISTORYSERVICESERVICE_QNAME = new QName("http://ibm.com/queryHistory/", "ProcessHistoryServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.1.66:50200/ProcessHistoryServiceService/ProcessHistoryService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSHISTORYSERVICESERVICE_WSDL_LOCATION = url;
        PROCESSHISTORYSERVICESERVICE_EXCEPTION = e;
    }

    public ProcessHistoryServiceService() {
        super(__getWsdlLocation(), PROCESSHISTORYSERVICESERVICE_QNAME);
    }

    public ProcessHistoryServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSHISTORYSERVICESERVICE_QNAME, features);
    }

    public ProcessHistoryServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSHISTORYSERVICESERVICE_QNAME);
    }

    public ProcessHistoryServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSHISTORYSERVICESERVICE_QNAME, features);
    }

    public ProcessHistoryServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessHistoryServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProcessHistoryService
     */
    @WebEndpoint(name = "ProcessHistoryServicePort")
    public ProcessHistoryService getProcessHistoryServicePort() {
        return super.getPort(new QName("http://ibm.com/queryHistory/", "ProcessHistoryServicePort"), ProcessHistoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProcessHistoryService
     */
    @WebEndpoint(name = "ProcessHistoryServicePort")
    public ProcessHistoryService getProcessHistoryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibm.com/queryHistory/", "ProcessHistoryServicePort"), ProcessHistoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSHISTORYSERVICESERVICE_EXCEPTION!= null) {
            throw PROCESSHISTORYSERVICESERVICE_EXCEPTION;
        }
        return PROCESSHISTORYSERVICESERVICE_WSDL_LOCATION;
    }

}
