
package com.ibm.service.form;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FormServiceService", targetNamespace = "http://ibm.com/form/service/", wsdlLocation = "http://10.6.1.66:50200/FormServiceService/FormService?wsdl")
public class FormServiceService
    extends Service
{

    private final static URL FORMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FORMSERVICESERVICE_EXCEPTION;
    private final static QName FORMSERVICESERVICE_QNAME = new QName("http://ibm.com/form/service/", "FormServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.6.1.66:50200/FormServiceService/FormService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FORMSERVICESERVICE_WSDL_LOCATION = url;
        FORMSERVICESERVICE_EXCEPTION = e;
    }

    public FormServiceService() {
        super(__getWsdlLocation(), FORMSERVICESERVICE_QNAME);
    }

    public FormServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FORMSERVICESERVICE_QNAME, features);
    }

    public FormServiceService(URL wsdlLocation) {
        super(wsdlLocation, FORMSERVICESERVICE_QNAME);
    }

    public FormServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FORMSERVICESERVICE_QNAME, features);
    }

    public FormServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FormServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FormService
     */
    @WebEndpoint(name = "FormServicePort")
    public FormService getFormServicePort() {
        return super.getPort(new QName("http://ibm.com/form/service/", "FormServicePort"), FormService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FormService
     */
    @WebEndpoint(name = "FormServicePort")
    public FormService getFormServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ibm.com/form/service/", "FormServicePort"), FormService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FORMSERVICESERVICE_EXCEPTION!= null) {
            throw FORMSERVICESERVICE_EXCEPTION;
        }
        return FORMSERVICESERVICE_WSDL_LOCATION;
    }

}
